### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by martin0327** [mintutu/leetcode-country-ranking#15]
![image](https://user-images.githubusercontent.com/16455262/208926582-8c96c5b6-4c96-4543-8ec6-9b3a7c9ad37b.png)

**Comment by bimal-parajuli** [comment]
This application was hosted on Heroku. Possibly using the free dynos. Back in November, Heroku removed all the free options. Affected applications were warned with a deadline for migrating to paid plan and the ones who didn't move to the free plan were eventually removed from the platform.

This application is also probably affected by the same move from Heroku. All the source code is here in this repo. @martin0327 If you want, may be you can host this code yourself somewhere and rerun the application by appropriately crediting the original author of the project. @mintutu 

https://blog.heroku.com/next-chapter#:~:text=Starting%20November%2028%2C%202022%2C%20we%20plan%20to%20stop%20offering%20free%20product%20plans%20and%20plan%20to%20start%20shutting%20down%20free%20dynos%20and%20data%20services

**Comment by mintutu** [comment]
thanks @bimal-parajuli for your explanation. It's true. The site was down due to Heroku stopping free dynos. I've changed to use render. New URL is: https://leetcode-country-ranking.onrender.com
